'use client'

import Footer from './components/Footer'
import Header from './components/Header'
import './styles/globals.css'

import customTheme from './theme/theme'
import { ThemeProvider, CssBaseline } from '@mui/material'

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="pt-BR">
      <head>
        <title>The Rick and Morty API</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </head>
      <ThemeProvider theme={customTheme}>
        <body id="__next">
          <CssBaseline />
          <Header />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  )
}

export default RootLayout
